name: Release

on:
  release:
    types: [prereleased]
  push:
    paths:
      - ".github/workflows/*.yml"

jobs:
  build:
    strategy:
      matrix:
        # Include amd64 on all platforms.
        go_version:
          - 1.18.0
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare
        run: |
          mkdir -p dist

      - name: build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: dist
          prefix: cftestor
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default

      - name: Create ZIP archive
        run: |
          cd dist
          for item in cftestor-*; do
              prefix=$(echo "${item}" | sed 's/\.exe$//' | sed 's/windows-4\.0-/windows-/')
              zip -9vr ${prefix}.zip "${item}"
              for t in md5 sha1 sha256 sha512; do
                  openssl dgst -${t} ${prefix}.zip | sed 's/([^)]*)//g' | sed 's/= /=/' >> ${prefix}.zip.dgst
              done
              rm "${item}"
          done          
          cd ..

      - name: Upload files to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          file: ./dist/cftestor-*
          tag: ${{ github.ref }}
